apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-pass
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/rnSriovpass
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "sriov-pass-network",
    "type": "sriov",
    "ipam": {
      "type": "host-local",
      "subnet": "172.16.6.0/24",
      "rangeStart": "172.16.6.101",
      "rangeEnd": "172.16.6.120"
    }
  }'
