apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n3 
  namespace: open5gs
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "N3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.16.11.0/24",
        "rangeStart": "172.16.11.101",
        "rangeEnd": "172.16.11.120"
      }
    }'
