amf:
  ip: 172.16.10.203

interfaces:
  n3:
    dev: net1

podAnnotations: { k8s.v1.cni.cncf.io/networks: '[ { "name": "n3","ips": [ "172.16.11.102/24" ] } ]' }

mcc: '999'
mnc: '70'
sst: 1
sd: "0x111111"
tac: '0001'

ues:
  enabled: true
  count: 2
  initialMSISDN: '0000000001'
