hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: false

smf:
  config:
    pcrf:
      enabled: false
    upf:
      pfcp:
        addr: 192.168.25.25
        hostname: 192.168.25.25
  services:
    pfcp:
      type: LoadBalancer
      loadBalancerIP: 192.168.25.24
    gtpc:
      type: LoadBalancer
      loadBalancerIP: 192.168.25.26
    frdi:
      type: LoadBalancer
      loadBalancerIP: 192.168.25.27

amf:
  services:
    ngap:
      type: NodePort
      nodePorts:
        ngap: "30001" 

upf:
  enabled: false

sgwc:
  enabled: false

sgwu:
  enabled: false

webui:
  ingress:
    enabled: false

populate:
  enabled: true
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
