apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool1
spec:
  addresses:
  - 172.16.10.40-172.16.10.44

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2example
spec:
  ipAddressPools:
  - pool1
